import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'page',
  title: 'Website Pages',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Page Name', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({ name: 'pageKey', title: 'Page Key', type: 'string', options: { list: [
      { title: 'Homepage', value: 'homepage' },
      { title: 'Uitgaan', value: 'uitgaan' },
      { title: 'Cocktail Workshop', value: 'cocktailWorkshop' },
      { title: 'Ruimte Huren / Event Space', value: 'eventSpace' },
      { title: 'Contact', value: 'contact' },
      { title: 'Vacatures', value: 'vacatures' },
      { title: 'House Rules', value: 'houseRules' },
      { title: 'Fotos', value: 'fotos' },
    ] }, validation: (Rule) => Rule.required() }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title' } }),
    defineField({ name: 'headlineNl', title: 'Headline NL', type: 'string' }),
    defineField({ name: 'headlineEn', title: 'Headline EN', type: 'string' }),
    defineField({ name: 'introNl', title: 'Intro NL', type: 'text', rows: 4 }),
    defineField({ name: 'introEn', title: 'Intro EN', type: 'text', rows: 4 }),
    defineField({ name: 'bodyNl', title: 'Body NL', type: 'text', rows: 8 }),
    defineField({ name: 'bodyEn', title: 'Body EN', type: 'text', rows: 8 }),
    defineField({ name: 'primaryButtonNl', title: 'Primary Button NL', type: 'string' }),
    defineField({ name: 'primaryButtonEn', title: 'Primary Button EN', type: 'string' }),
    defineField({ name: 'secondaryButtonNl', title: 'Secondary Button NL', type: 'string' }),
    defineField({ name: 'secondaryButtonEn', title: 'Secondary Button EN', type: 'string' }),
    defineField({ name: 'heroImage', title: 'Hero Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'galleryImages', title: 'Gallery Images', type: 'array', of: [{ type: 'image', options: { hotspot: true } }] }),
    defineField({ name: 'seoTitleNl', title: 'SEO Title NL', type: 'string' }),
    defineField({ name: 'seoTitleEn', title: 'SEO Title EN', type: 'string' }),
    defineField({ name: 'seoDescriptionNl', title: 'SEO Description NL', type: 'text', rows: 3 }),
    defineField({ name: 'seoDescriptionEn', title: 'SEO Description EN', type: 'text', rows: 3 }),
    defineField({ name: 'ogImage', title: 'Social Share Image', type: 'image', options: { hotspot: true } }),
  ],
  preview: { select: { title: 'title', subtitle: 'pageKey', media: 'heroImage' } },
})
